dbfilename redis_queue.rdb
dir /Users/vkm/Documents/Work/github/frappe-bench/config/pids
pidfile /Users/vkm/Documents/Work/github/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11002

aclfile /Users/vkm/Documents/Work/github/frappe-bench/config/redis_queue.acl
